// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpIhXnTbJn_A9Yc_gNR9Pjb2OOPTjZwKU',
    appId: '1:249153786032:web:8fdbddbc5a667711caeb75',
    messagingSenderId: '249153786032',
    projectId: 'spendwise-app-e76d4',
    authDomain: 'spendwise-app-e76d4.firebaseapp.com',
    storageBucket: 'spendwise-app-e76d4.firebasestorage.app',
    measurementId: 'G-62PWLY7H7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjEFBXyEE1QOkiucHVx3PNbGpHMfPL9QU',
    appId: '1:249153786032:android:c9bf2767d8c08c0ecaeb75',
    messagingSenderId: '249153786032',
    projectId: 'spendwise-app-e76d4',
    storageBucket: 'spendwise-app-e76d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0AwAUWrB9-oZ7Acsc7Mv6Ef5weX6s0PQ',
    appId: '1:249153786032:ios:9248c6febfb93529caeb75',
    messagingSenderId: '249153786032',
    projectId: 'spendwise-app-e76d4',
    storageBucket: 'spendwise-app-e76d4.firebasestorage.app',
    iosBundleId: 'com.benjamin.spendwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0AwAUWrB9-oZ7Acsc7Mv6Ef5weX6s0PQ',
    appId: '1:249153786032:ios:be4a82b46041008fcaeb75',
    messagingSenderId: '249153786032',
    projectId: 'spendwise-app-e76d4',
    storageBucket: 'spendwise-app-e76d4.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpIhXnTbJn_A9Yc_gNR9Pjb2OOPTjZwKU',
    appId: '1:249153786032:web:907bd5e925214566caeb75',
    messagingSenderId: '249153786032',
    projectId: 'spendwise-app-e76d4',
    authDomain: 'spendwise-app-e76d4.firebaseapp.com',
    storageBucket: 'spendwise-app-e76d4.firebasestorage.app',
    measurementId: 'G-33LC0XVG6Q',
  );
}
